# Generated by Django 4.2.7 on 2024-12-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when notification was created'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(help_text='Full content of the notification'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False, help_text='Indicates if the notification has been read'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(help_text='Brief heading of the notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when notification was last updated'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='task_assigned',
            field=models.BooleanField(default=True, help_text='Whether to receive task assignment notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='task_completed',
            field=models.BooleanField(default=True, help_text='Whether to receive task completion notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='task_updated',
            field=models.BooleanField(default=True, help_text='Whether to receive task update notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(help_text='User whose preferences these are', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.ForeignKey(help_text='Category of notification', on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype'),
        ),
    ]
