# Generated by Django 4.2.7 on 2024-12-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtype_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='task_assigned',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='task_completed',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='task_updated',
        ),
        migrations.AddField(
            model_name='notifications',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Priority level of the notification', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Whether to receive email notifications'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='enabled_types',
            field=models.ManyToManyField(help_text='Notification types that the user has enabled', related_name='subscribed_users', to='notifications.notificationtype'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Whether to receive push notifications'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(help_text='Brief heading of the notification', max_length=200),
        ),
    ]
