from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NotificationsViewSet, UserPreferencesViewSet

"""
URL configuration for the notifications app.

This module defines the URL patterns for the REST API endpoints.
It uses Django REST Framework's DefaultRouter to automatically generate
the URLs for the ViewSets.

Generated URLs:
    - /notifications/
        - GET: List all notifications for the user
        - POST: Create a new notification
    - /notifications/{id}/
        - GET: Retrieve a specific notification
        - PUT/PATCH: Update a notification
        - DELETE: Delete a notification
    - /preferences/
        - GET: Get user's notification preferences
        - POST: Create user preferences
    - /preferences/{id}/
        - GET: Get specific preference settings
        - PUT/PATCH: Update preference settings
        - DELETE: Delete preference settings
"""

# Create a router instance
router = DefaultRouter()

# Register the viewsets with the router
router.register(
    r'notifications',  # URL prefix for notification endpoints
    NotificationsViewSet,  # ViewSet class to handle notifications
    basename='notification'  # Base name for URL reversing
)
router.register(
    r'preferences',  # URL prefix for preference endpoints
    UserPreferencesViewSet,  # ViewSet class to handle preferences
    basename='preference'  # Base name for URL reversing
)

# URL patterns for the notifications app
urlpatterns = [
    # Include all routes generated by the router
    path('', include(router.urls)),
    path('notifications/', NotificationsViewSet.as_view({'post': 'create', 'get': 'list'}), name='notifications'),
    path('preferences/', UserPreferencesViewSet.as_view({'post': 'create', 'get': 'retrieve'}), name='user-preferences'),
]
